@env=local
### Authors ###
#ksiazki 8082
#autorzy 8081
#gateway 8080

# Get all authors
GET http://localhost:8080/api/authors
Accept: application/json

###

#get author
GET http://localhost:8080/api/authors/King
Accept: application/json
###

# Create a new author
POST http://localhost:8080/api/authors
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe"
}

###
GET http://localhost:8080/api/authors
Accept: application/json
###

# Update an existing author
PUT http://localhost:8080/api/authors/Doe
Content-Type: application/json

{
  "name": "Jane",
  "surname": "Smith"
}

###
GET http://localhost:8080/api/authors
Accept: application/json
###

# Delete an author
#DELETE http://localhost:8080/api/authors/King
#no longer works for surname

###
#
GET http://localhost:8080/api/authors
Accept: application/json



### Books ###


# Get all books
GET http://localhost:8080/api/books
Accept: application/json

###

#books by author
GET http://localhost:8080/api/authors/Rowling/books
Accept: application/json

###

# Add a new book to an author
POST http://localhost:8080/api/authors/cb2bee33-2770-4aac-8c09-b21e065e36c8/books
Content-Type: application/json

{
  "title": "My New Book",
  "genre": "Fiction"
}

###
GET http://localhost:8080/api/authors/Rowling/books
Accept: application/json

###

# Delete a book by title
DELETE http://localhost:8080/api/books/Dune

###
# Get all books
GET http://localhost:8080/api/books
Accept: application/json


### DELETE a book by title
DELETE http://localhost:8080/api/books/My%20New%20Book
Accept: application/json

